/* i18n.js — full bilingual copy, ported verbatim from the handoff source (RO default). */
window.STR = {
    en: {
      tagline:'Daily medicines, together', welcome:'Welcome back', signInSub:"Sign in to your family's daily list.", familyName:'The Bennett family', email:'Email', password:'Password', signIn:'Sign in', help:'Trouble signing in? Call Sarah on (555) 010-2929',
      navToday:'Today', navHistory:'History', navManage:'Manage', navSettings:'Settings',
      greetMorning:'Good morning', greetAfternoon:'Good afternoon', greetEvening:'Good evening',
      daysTitle:"{name}'s day", weekTitle:"{name}'s week",
      sumAllDone:'All done for today', sumNothing:'Nothing scheduled', sumPillLeft:'{n} pill left to take', sumPillsLeft:'{n} pills left to take', sumTaken:'{done} of {total} taken', sumNotTaken:'{n} not taken', sumAddManage:'Add items in Manage',
      remOverdue:'{group} medicines are overdue', remDue:'{group} medicines are due now', remNext:'Next reminder · {group} at {time}', remAllDone:'All done for today — lovely work', remAllDonePlain:'All done for today',
      badgeAllDone:'All done', badgeDue:'Due now', badgeOverdue:'Overdue', badgeSoon:'Coming up',
      reminderWord:'Reminder {time}', secActivities:'Activities',
      take:'Take {n}', forPurpose:'for {purpose}', takenAt:'Taken at {time}', takenWord:'Taken', markedNot:'Marked not taken', doneAt:'Done at {time}', doneWord:'Done', markedNotAct:'Not done',
      btnTaken:'Taken', btnDidnt:"Didn't take", btnDone:'Done', btnDidntDo:"Didn't do", btnChange:'Change', editTime:'Edit time',
      histKicker:'This week', takenThisWeek:'taken this week', ofDoses:'of {n} doses', weekTaken:'of {n} taken this week', legendTaken:'Taken', legendNot:'Not taken', legendNo:'No record', legendNA:'Not scheduled', tapCorrect:'Tap any square to correct it — saved for the whole family.', cancelChanges:'Cancel changes', saveChanges:'Save changes', viewAll:'View entire history', allHistTitle:'Full history', last30:'Last 30 days', weekThis:'This week', weekLast:'Last week', prevWeek:'Previous week', nextWeek:'Next week', close:'Close', noRecordsWeek:'Nothing scheduled this week.', fRepeat:'Repeats', repDaily:'Every day', repWeekly:'Weekly', repMonthly:'Monthly', fDays:'On these days', fDom:'Day of the month', fEnd:'Ends (optional)', endNever:'No end', endOnDate:'On a date', endAfter:'After N times', fEndCount:'Number of times', endTimes:'times', domLabel:'day {n}', until:'until {date}', untilCount:'{n} times', worthLook:'Worth a look', missNot:'not taken', missNo:'no record',
      mngKicker:'Set up', mngTitle:'Manage', tabLists:'Lists', listOf:"{name}'s list", addBtn:'Add', familyMembers:'Family members', familyNote:'Everyone signed in to this family can view and update any list.', addMember:'Add a family member', fixTitle:'Fixing a mistake', fixBody:'Open History and tap any day to change whether something was taken.', goHistoryBtn:'Go to History', signOut:'Sign out', noList:"Nothing on {name}'s list yet.", addFirst:'Add the first item', notifTitle:'Notifications', notifNote:'Reminders go to the linked Telegram chats for this person.', linkTelegram:'Link Telegram', notifNone:'No linked account yet.', unlinkWord:'Remove', verifiedWord:'Linked', pendingWord:'Waiting…', notifMax:'Up to 3 accounts per person.', linkOpen:'Open Telegram', linkHint:'Telegram is opening — press Start there, then come back and tap Refresh.', refreshWord:'Refresh', notifyNow:'Notify now', notifySent:'Reminder sent ({n})', notifyNoChannel:'No Telegram linked for this person yet.', shareTitle:'Shared with', shareNote:'Add a family account by email — they can view and update this list and link their own Telegram to be notified too.', shareAdd:'Share', shareEmailPh:'email address', shareAdded:'Shared', shareNoUser:'No account with that email.', ownerWord:'Owner', editorWord:'Can edit', photoError:'Could not upload the photo.', addNote:'Add a note', notePh:'e.g. 120/80', noteToday:'Notes for today', noteTodayPh:'Anything to remember about today…', exportTitle:'Export history', exportNote:"Download {name}'s history as a spreadsheet (CSV) for the doctor.", export30:'30 days', export90:'90 days', exportAll:'1 year',
      setKicker:'Preferences', setTitle:'Settings', setLanguage:'Language', setTextSize:'Text size', tsStandard:'Standard', tsLarge:'Large', tsXL:'Extra large', setPhotos:'Show pill photos', onWord:'On', offWord:'Off',
      editAdd:'Add to the list', editEdit:'Edit item', fName:'Name', fType:'Type', fHowMany:'How many', fWhen:'When', fTime:'Time', fFor:"What it's for (optional)", fNote:'Special note (optional)', cancel:'Cancel', save:'Save', phName:'e.g. Metformin, or Back exercise', phFor:'e.g. Blood pressure', phNote:'e.g. take with food', fPhoto:'Photo (optional)', addPhoto:'Add photo', changePhoto:'Change photo', removePhoto:'Remove', typeMedicine:'Medicine', typeActivity:'Activity / task',
      personAddTitle:'Add a family member', personAddSub:"They'll appear in the switcher with an empty list you can fill in.", fRelationship:'Relationship', addPersonBtn:'Add', phPersonName:'e.g. Eleanor', phRelationship:'e.g. Mother', personEditTitle:'Edit family member', savePersonBtn:'Save', editPerson:'Edit',
      groupMorning:'Morning', groupNoon:'Midday', groupEvening:'Evening', groupBedtime:'Bedtime',
    },
    ro: {
      tagline:'Medicamente zilnice, împreună', welcome:'Bine ai revenit', signInSub:'Conectează-te la lista zilnică a familiei.', familyName:'Familia Bennett', email:'E-mail', password:'Parolă', signIn:'Conectează-te', help:'Probleme la conectare? Sun-o pe Sarah la (555) 010-2929',
      navToday:'Azi', navHistory:'Istoric', navManage:'Gestionare', navSettings:'Setări',
      greetMorning:'Bună dimineața', greetAfternoon:'Bună ziua', greetEvening:'Bună seara',
      daysTitle:'Ziua lui {name}', weekTitle:'Săptămâna lui {name}',
      sumAllDone:'Gata pe azi', sumNothing:'Nimic programat', sumPillLeft:'Mai ai {n} pastilă de luat', sumPillsLeft:'Mai ai {n} pastile de luat', sumTaken:'{done} din {total} luate', sumNotTaken:'{n} neluate', sumAddManage:'Adaugă din Gestionare',
      remOverdue:'Medicamentele de {group} sunt întârziate', remDue:'Medicamentele de {group} trebuie luate acum', remNext:'Următoarea amintire · {group} la {time}', remAllDone:'Gata pe azi — bravo!', remAllDonePlain:'Gata pe azi!',
      badgeAllDone:'Gata', badgeDue:'Acum', badgeOverdue:'Întârziat', badgeSoon:'Urmează',
      reminderWord:'Reamintire la {time}', secActivities:'Activități',
      take:'ia {n}', forPurpose:'pentru {purpose}', takenAt:'Luat la {time}', takenWord:'Luat', markedNot:'Marcat ca neluat', doneAt:'Făcut la {time}', doneWord:'Făcut', markedNotAct:'Nu am făcut',
      btnTaken:'Am luat', btnDidnt:'Nu am luat', btnDone:'Am făcut', btnDidntDo:'Nu am făcut', btnChange:'Modifică', editTime:'Modifică ora',
      histKicker:'Săptămâna aceasta', takenThisWeek:'luate săptămâna asta', ofDoses:'din {n} doze', weekTaken:'din {n} luate săpt. asta', legendTaken:'Luat', legendNot:'Neluat', legendNo:'Fără date', legendNA:'Nu se aplică', tapCorrect:'Apasă orice pătrat pentru a corecta — salvat pentru toată familia.', cancelChanges:'Anulează modificările', saveChanges:'Salvează modificările', viewAll:'Vezi tot istoricul', allHistTitle:'Istoric complet', last30:'Ultimele 30 de zile', weekThis:'Săptămâna asta', weekLast:'Săptămâna trecută', prevWeek:'Săptămâna anterioară', nextWeek:'Săptămâna următoare', close:'Închide', noRecordsWeek:'Nimic programat în această săptămână.', fRepeat:'Repetare', repDaily:'În fiecare zi', repWeekly:'Săptămânal', repMonthly:'Lunar', fDays:'În aceste zile', fDom:'Ziua lunii', fEnd:'Se termină (opțional)', endNever:'Fără sfârșit', endOnDate:'La o dată', endAfter:'După N ori', fEndCount:'Număr de ori', endTimes:'ori', domLabel:'ziua {n}', until:'până la {date}', untilCount:'{n} ori', worthLook:'De verificat', missNot:'neluat', missNo:'fără date',
      mngKicker:'Configurare', mngTitle:'Gestionare', tabLists:'Liste', listOf:'Lista lui {name}', addBtn:'Adaugă', familyMembers:'Membrii familiei', familyNote:'Toți cei conectați la această familie pot vedea și actualiza orice listă.', addMember:'Adaugă un membru', fixTitle:'Corectarea unei greșeli', fixBody:'Deschide Istoric și apasă orice zi pentru a schimba dacă ceva a fost luat.', goHistoryBtn:'Mergi la Istoric', signOut:'Deconectează-te', noList:'Nimic în lista lui {name} încă.', addFirst:'Adaugă primul element', notifTitle:'Notificări', notifNote:'Mementourile ajung pe conturile de Telegram legate pentru această persoană.', linkTelegram:'Leagă Telegram', notifNone:'Niciun cont legat încă.', unlinkWord:'Scoate', verifiedWord:'Conectat', pendingWord:'Se așteaptă…', notifMax:'Maxim 3 conturi per persoană.', linkOpen:'Deschide Telegram', linkHint:'Se deschide Telegram — apasă Start acolo, apoi revino și apasă Reîmprospătează.', refreshWord:'Reîmprospătează', notifyNow:'Trimite acum', notifySent:'Memento trimis ({n})', notifyNoChannel:'Niciun Telegram legat pentru această persoană încă.', shareTitle:'Partajat cu', shareNote:'Adaugă un cont de familie după e-mail — poate vedea și actualiza lista și își poate lega propriul Telegram pentru a fi notificat.', shareAdd:'Partajează', shareEmailPh:'adresă de e-mail', shareAdded:'Partajat', shareNoUser:'Niciun cont cu acest e-mail.', ownerWord:'Proprietar', editorWord:'Poate edita', photoError:'Nu am putut încărca poza.', addNote:'Adaugă o notă', notePh:'ex. 120/80', noteToday:'Note pentru azi', noteTodayPh:'Ceva de reținut despre azi…', exportTitle:'Exportă istoricul', exportNote:'Descarcă istoricul lui {name} ca foaie de calcul (CSV) pentru medic.', export30:'30 de zile', export90:'90 de zile', exportAll:'1 an',
      setKicker:'Preferințe', setTitle:'Setări', setLanguage:'Limbă', setTextSize:'Mărimea textului', tsStandard:'Standard', tsLarge:'Mare', tsXL:'Foarte mare', setPhotos:'Arată pozele pastilelor', onWord:'Da', offWord:'Nu',
      editAdd:'Adaugă în listă', editEdit:'Modifică elementul', fName:'Nume', fType:'Tip', fHowMany:'Câte', fWhen:'Când', fTime:'Ora', fFor:'Pentru ce este (opțional)', fNote:'Notă specială (opțional)', cancel:'Anulează', save:'Salvează', phName:'ex. Metformin sau Exerciții pentru spate', phFor:'ex. Tensiune arterială', phNote:'ex. a se lua cu mâncare', fPhoto:'Poză (opțional)', addPhoto:'Adaugă poză', changePhoto:'Schimbă poza', removePhoto:'Elimină', typeMedicine:'Medicament', typeActivity:'Activitate / sarcină',
      personAddTitle:'Adaugă un membru', personAddSub:'Va apărea în selector cu o listă goală pe care o poți completa.', fRelationship:'Relație', addPersonBtn:'Adaugă', phPersonName:'ex. Eleanor', phRelationship:'ex. Mama', personEditTitle:'Modifică membrul', savePersonBtn:'Salvează', editPerson:'Modifică',
      groupMorning:'Dimineață', groupNoon:'Prânz', groupEvening:'Seară', groupBedtime:'Culcare',
    },
};
// app-only extras not in the handoff STR:
window.STR.en.brand='Alongside'; window.STR.en.orDivider='or'; window.STR.en.googleBtn='Continue with Google'; window.STR.en.people='People'; window.STR.en.noPeople='No people yet. Add them from the admin page.'; window.STR.en.comingSoon='Coming soon — building this section.'; window.STR.en.admin='Admin';
window.STR.ro.brand='Alongside'; window.STR.ro.orDivider='sau'; window.STR.ro.googleBtn='Continuă cu Google'; window.STR.ro.people='Persoane'; window.STR.ro.noPeople='Nicio persoană încă. Adaug-o din pagina de administrare.'; window.STR.ro.comingSoon='În curând — construim această secțiune.'; window.STR.ro.admin='Administrare';
